const GAME_MUSIC = new Audio('assets/audio/game_music.mp3'); //https://freesound.org/people/Timbre/sounds/406894/
const MENU_MUSIC = new Audio('assets/audio/menu_music.mp3'); //https://freesound.org/people/Timbre/sounds/94564/
const BOSS_MUSIC = new Audio('assets/audio/boss_music.mp3'); //https://freesound.org/people/Timbre/sounds/146903/
const GAME_OVER_MUSIC = new Audio('assets/audio/game_over1.mp3'); //1.
const VICTORY_MUSIC = new Audio('assets/audio/victory.mp3'); //https://freesound.org/people/Peanut_Shaman/sounds/581415/
const WALKING_SOUND = new Audio('assets/audio/running.mp3');
const JUMPING_SOUND = new Audio('assets/audio/jump.mp3');
const HIT_SOUND = new Audio('assets/audio/hit.mp3'); //HIT SOUND attribution https://freesound.org/people/Cigaro30/sounds/420932/
const SLEEPING_SOUND = new Audio('assets/audio/sleep.mp3');
const THROWING_SOUND = new Audio('assets/audio/throwing.mp3');